# Generated by Django 3.2.6 on 2022-02-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
